class Countries {
  final String name;
  final String nameAr;
  final String dialCode;
  final String currency;
  final String iso2;
  final String iso3;
  final bool isArabianCountry;
  final bool isKhalijiCountry;
  final String flag;
  final int order;

  Countries({
    required this.name,
    required this.nameAr,
    required this.dialCode,
    required this.currency,
    required this.iso2,
    required this.iso3,
    required this.isArabianCountry,
    required this.isKhalijiCountry,
    required this.flag,
    required this.order,
  });

  factory Countries.fromJson(Map<String, dynamic> json) {
    return Countries(
      name: json['name'],
      nameAr: json['name_ar'],
      dialCode: json['dial_code'],
      currency: json['currency'],
      iso2: json['iso2'],
      iso3: json['iso2'],
      isArabianCountry: json['is_arabian_country'],
      isKhalijiCountry: json['is_khaliji_country'],
      flag: json['flag'],
      order: json['order'],
    );
  }
  Map<String, dynamic> toJson() => {
        'name': name,
        'name_ar': nameAr,
        'dial_code': dialCode,
        'currency': currency,
        'iso2': iso2,
        'iso3': iso3,
        'is_arabian_country': isArabianCountry,
        'is_khaliji_country': isKhalijiCountry,
        'flag': flag,
        'order': order,
      };
}

final countriesList = [
  Countries(
    name: 'Afghanistan',
    nameAr: 'أفغانستان',
    dialCode: '+93',
    currency: 'AFN',
    iso2: 'AF',
    iso3: 'AFG',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇫',
    order: 0,
  ),
  Countries(
    name: 'Albania',
    nameAr: 'ألبانيا',
    dialCode: '+355',
    currency: 'ALL',
    iso2: 'AL',
    iso3: 'ALB',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇱',
    order: 0,
  ),
  Countries(
    name: 'Algeria',
    nameAr: 'الجزائر',
    dialCode: '+213',
    currency: 'DZD',
    iso2: 'DZ',
    iso3: 'DZA',
    isArabianCountry: true,
    isKhalijiCountry: false,
    flag: '🇩🇿',
    order: 13,
  ),
  Countries(
    name: 'Andorra',
    nameAr: 'أندورا',
    dialCode: '+376',
    currency: 'EUR',
    iso2: 'AD',
    iso3: 'AND',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇩',
    order: 0,
  ),
  Countries(
    name: 'Angola',
    nameAr: 'أنغولا',
    dialCode: '+244',
    currency: 'AOA',
    iso2: 'AO',
    iso3: 'AGO',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇴',
    order: 0,
  ),
  Countries(
    name: 'Anguilla',
    nameAr: 'أنغويلا',
    dialCode: '+1264',
    currency: 'XCD',
    iso2: 'AI',
    iso3: 'AIA',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇮',
    order: 0,
  ),
  Countries(
    name: 'Antigua and Barbuda',
    nameAr: 'أنتيغوا وبربودا',
    dialCode: '+1268',
    currency: 'XCD',
    iso2: 'AG',
    iso3: 'ATG',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇬',
    order: 0,
  ),
  Countries(
    name: 'Argentina',
    nameAr: 'الأرجنتين',
    dialCode: '+54',
    currency: 'ARS',
    iso2: 'AR',
    iso3: 'ARG',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇷',
    order: 0,
  ),
  Countries(
    name: 'Armenia',
    nameAr: 'أرمينيا',
    dialCode: '+374',
    currency: 'AMD',
    iso2: 'AM',
    iso3: 'ARM',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇲',
    order: 0,
  ),
  Countries(
    name: 'Aruba',
    nameAr: 'أروبا',
    dialCode: '+297',
    currency: 'AWG',
    iso2: 'AW',
    iso3: 'ABW',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇼',
    order: 0,
  ),
  Countries(
    name: 'Australia',
    nameAr: 'أستراليا',
    dialCode: '+61',
    currency: 'AUD',
    iso2: 'AU',
    iso3: 'AUS',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇺',
    order: 0,
  ),
  Countries(
    name: 'Austria',
    nameAr: 'النمسا',
    dialCode: '+43',
    currency: 'EUR',
    iso2: 'AT',
    iso3: 'AUT',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇹',
    order: 0,
  ),
  Countries(
    name: 'Azerbaijan',
    nameAr: 'أذربيجان',
    dialCode: '+994',
    currency: 'AZN',
    iso2: 'AZ',
    iso3: 'AZE',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇦🇿',
    order: 0,
  ),
  Countries(
    name: 'Bahamas',
    nameAr: 'جزر البهاما',
    dialCode: '+1242',
    currency: 'BSD',
    iso2: 'BS',
    iso3: 'BHS',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇸',
    order: 0,
  ),
  Countries(
    name: 'Bahrain',
    nameAr: 'البحرين',
    dialCode: '+973',
    currency: 'BHD',
    iso2: 'BH',
    iso3: 'BHR',
    isArabianCountry: true,
    isKhalijiCountry: true,
    flag: '🇧🇭',
    order: 20,
  ),
  Countries(
    name: 'Bangladesh',
    nameAr: 'بنجلاديش',
    dialCode: '+880',
    currency: 'BDT',
    iso2: 'BD',
    iso3: 'BGD',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇩',
    order: 0,
  ),
  Countries(
    name: 'Barbados',
    nameAr: 'باربادوس',
    dialCode: '+1246',
    currency: 'BBD',
    iso2: 'BB',
    iso3: 'BRB',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇧',
    order: 0,
  ),
  Countries(
    name: 'Belarus',
    nameAr: 'بيلاروس',
    dialCode: '+375',
    currency: 'BYR',
    iso2: 'BY',
    iso3: 'BLR',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇾',
    order: 0,
  ),
  Countries(
    name: 'Belgium',
    nameAr: 'بلجيكا',
    dialCode: '+32',
    currency: 'EUR',
    iso2: 'BE',
    iso3: 'BEL',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇪',
    order: 0,
  ),
  Countries(
    name: 'Belize',
    nameAr: 'بيليز',
    dialCode: '+501',
    currency: 'BZD',
    iso2: 'BZ',
    iso3: 'BLZ',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇿',
    order: 0,
  ),
  Countries(
    name: 'Benin',
    nameAr: 'بنين',
    dialCode: '+229',
    currency: 'XOF',
    iso2: 'BJ',
    iso3: 'BEN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇯',
    order: 0,
  ),
  Countries(
    name: 'Bermuda',
    nameAr: 'برمودا',
    dialCode: '+1441',
    currency: 'BMD',
    iso2: 'BM',
    iso3: 'BMU',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇲',
    order: 0,
  ),
  Countries(
    name: 'Bhutan',
    nameAr: 'بوتان',
    dialCode: '+975',
    currency: 'BTN',
    iso2: 'BT',
    iso3: 'BTN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇹',
    order: 0,
  ),
  Countries(
    name: 'Bolivia',
    nameAr: 'بوليفيا',
    dialCode: '+591',
    currency: 'BOB',
    iso2: 'BO',
    iso3: 'BOL',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇴',
    order: 0,
  ),
  Countries(
    name: 'Bosnia and Herzegovina',
    nameAr: 'البوسنة والهرسك',
    dialCode: '+387',
    currency: 'BAM',
    iso2: 'BA',
    iso3: 'BIH',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇦',
    order: 0,
  ),
  Countries(
    name: 'Botswana',
    nameAr: 'بوتسوانا',
    dialCode: '+267',
    currency: 'BWP',
    iso2: 'BW',
    iso3: 'BWA',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇼',
    order: 0,
  ),
  Countries(
    name: 'Brazil',
    nameAr: 'البرازيل',
    dialCode: '+55',
    currency: 'BRL',
    iso2: 'BR',
    iso3: 'BRA',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇷',
    order: 0,
  ),
  Countries(
    name: 'British Indian Ocean Territory',
    nameAr: 'إقليم المحيط الهندي البريطاني',
    dialCode: '+246',
    currency: 'USD',
    iso2: 'IO',
    iso3: 'IOT',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇮🇴',
    order: 0,
  ),
  Countries(
    name: 'Brunei',
    nameAr: 'بروناي',
    dialCode: '+673',
    currency: 'BND',
    iso2: 'BN',
    iso3: 'BRN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇳',
    order: 0,
  ),
  Countries(
    name: 'Bulgaria',
    nameAr: 'بلغاريا',
    dialCode: '+359',
    currency: 'BGN',
    iso2: 'BG',
    iso3: 'BGR',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇬',
    order: 0,
  ),
  Countries(
    name: 'Burkina Faso',
    nameAr: 'بوركينا فاسو',
    dialCode: '+226',
    currency: 'XOF',
    iso2: 'BF',
    iso3: 'BFA',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇫',
    order: 0,
  ),
  Countries(
    name: 'Myanmar',
    nameAr: 'ميانمار',
    dialCode: '+95',
    currency: 'MMK',
    iso2: 'MM',
    iso3: 'MMR',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇲🇲',
    order: 0,
  ),
  Countries(
    name: 'Burundi',
    nameAr: 'بوروندي',
    dialCode: '+257',
    currency: 'BIF',
    iso2: 'BI',
    iso3: 'BDI',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇧🇮',
    order: 0,
  ),
  Countries(
    name: 'Cambodia',
    nameAr: 'كامبوديا',
    dialCode: '+855',
    currency: 'KHR',
    iso2: 'KH',
    iso3: 'KHM',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇰🇭',
    order: 0,
  ),
  Countries(
    name: 'Cameroon',
    nameAr: 'الكاميرون',
    dialCode: '+237',
    currency: 'XAF',
    iso2: 'CM',
    iso3: 'CMR',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇲',
    order: 0,
  ),
  Countries(
    name: 'Canada',
    nameAr: 'كندا',
    dialCode: '+1',
    currency: 'CAD',
    iso2: 'CA',
    iso3: 'CAN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇦',
    order: 0,
  ),
  Countries(
    name: 'Cape Verde',
    nameAr: 'الرأس الأخضر',
    dialCode: '+238',
    currency: 'CVE',
    iso2: 'CV',
    iso3: 'CPV',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇻',
    order: 0,
  ),
  Countries(
    name: 'Cayman Islands',
    nameAr: 'جزر كايمان',
    dialCode: '+1345',
    currency: 'KYD',
    iso2: 'KY',
    iso3: 'CYM',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇰🇾',
    order: 0,
  ),
  Countries(
    name: 'Central African Republic',
    nameAr: 'جمهورية أفريقيا الوسطى',
    dialCode: '+236',
    currency: 'XAF',
    iso2: 'CF',
    iso3: 'CAF',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇫',
    order: 0,
  ),
  Countries(
    name: 'Chad',
    nameAr: 'تشاد',
    dialCode: '+235',
    currency: 'XAF',
    iso2: 'TD',
    iso3: 'TCD',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇹🇩',
    order: 0,
  ),
  Countries(
    name: 'Christmas Island',
    nameAr: 'جزيرة الكريسماس',
    dialCode: '+61',
    currency: 'AUD',
    iso2: 'CX',
    iso3: 'CXR',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇽',
    order: 0,
  ),
  Countries(
    name: 'Cocos (Keeling) Islands',
    nameAr: 'جزر الكوكوس (كيلين)',
    dialCode: '+61',
    currency: 'AUD',
    iso2: 'CC',
    iso3: 'CCK',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇨',
    order: 0,
  ),
  Countries(
    name: 'Cook Islands',
    nameAr: 'جزر كوك',
    dialCode: '+682',
    currency: 'NZD',
    iso2: 'CK',
    iso3: 'COK',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇰',
    order: 0,
  ),
  Countries(
    name: 'Chile',
    nameAr: 'تشيلي',
    dialCode: '+56',
    currency: 'CLP',
    iso2: 'CL',
    iso3: 'CHL',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇱',
    order: 0,
  ),
  Countries(
    name: 'China',
    nameAr: 'الصين',
    dialCode: '+86',
    currency: 'CNY',
    iso2: 'CN',
    iso3: 'CHN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇳',
    order: 0,
  ),
  Countries(
    name: 'Colombia',
    nameAr: 'كولومبيا',
    dialCode: '+57',
    currency: 'COP',
    iso2: 'CO',
    iso3: 'COL',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇴',
    order: 0,
  ),
  Countries(
    name: 'Comoros',
    nameAr: 'جزر القمر',
    dialCode: '+269',
    currency: 'KMF',
    iso2: 'KM',
    iso3: 'COM',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇰🇲',
    order: 0,
  ),
  Countries(
    name: 'Congo',
    nameAr: 'الكونغو',
    dialCode: '+242',
    currency: 'XAF',
    iso2: 'CG',
    iso3: 'COG',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇬',
    order: 0,
  ),
  Countries(
    name: 'Costa Rica',
    nameAr: 'كوستاريكا',
    dialCode: '+506',
    currency: 'CRC',
    iso2: 'CR',
    iso3: 'CRI',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇷',
    order: 0,
  ),
  Countries(
    name: 'Croatia',
    nameAr: 'كرواتيا',
    dialCode: '+385',
    currency: 'HRK',
    iso2: 'HR',
    iso3: 'HRV',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇭🇷',
    order: 0,
  ),
  Countries(
    name: 'Cuba',
    nameAr: 'كوبا',
    dialCode: '+53',
    currency: 'CUP',
    iso2: 'CU',
    iso3: 'CUB',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇺',
    order: 0,
  ),
  Countries(
    name: 'Cyprus',
    nameAr: 'قبرص',
    dialCode: '+357',
    currency: 'EUR',
    iso2: 'CY',
    iso3: 'CYP',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇾',
    order: 0,
  ),
  Countries(
    name: 'Czech Republic',
    nameAr: 'جمهورية التشيك',
    dialCode: '+420',
    currency: 'CZK',
    iso2: 'CZ',
    iso3: 'CZE',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇨🇿',
    order: 0,
  ),
  Countries(
    name: 'Denmark',
    nameAr: 'الدانمارك',
    dialCode: '+45',
    currency: 'DKK',
    iso2: 'DK',
    iso3: 'DNK',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇩🇰',
    order: 0,
  ),
  Countries(
    name: 'Djibouti',
    nameAr: 'جيبوتي',
    dialCode: '+253',
    currency: 'DJF',
    iso2: 'DJ',
    iso3: 'DJI',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇩🇯',
    order: 0,
  ),
  Countries(
    name: 'Dominica',
    nameAr: 'دومينيكا',
    dialCode: '+1767',
    currency: 'XCD',
    iso2: 'DM',
    iso3: 'DMA',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇩🇲',
    order: 0,
  ),
  Countries(
    name: 'Dominican Republic',
    nameAr: 'جمهورية الدومينيكان',
    dialCode: '+1849',
    currency: 'DOP',
    iso2: 'DO',
    iso3: 'DOM',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇩🇴',
    order: 0,
  ),
  Countries(
    name: 'Timor-Leste',
    nameAr: 'تيمور الشرقية',
    dialCode: '+670',
    currency: 'USD',
    iso2: 'TL',
    iso3: 'TLS',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇹🇱',
    order: 0,
  ),
  Countries(
    name: 'Tokelau',
    nameAr: 'توكيلاو',
    dialCode: '+690',
    currency: 'NZD',
    iso2: 'TK',
    iso3: 'TKL',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇹🇰',
    order: 0,
  ),
  Countries(
    name: 'Turks and Caicos Islands',
    nameAr: 'جزر تركس وكايكوس',
    dialCode: '+1649',
    currency: 'USD',
    iso2: 'TC',
    iso3: 'TCA',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇹🇨',
    order: 0,
  ),
  Countries(
    name: 'Ecuador',
    nameAr: 'إكوادور',
    dialCode: '+593',
    currency: 'USD',
    iso2: 'EC',
    iso3: 'ECU',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇪🇨',
    order: 0,
  ),
  Countries(
    name: 'Egypt',
    nameAr: 'مصر',
    dialCode: '+20',
    currency: 'EGP',
    iso2: 'EG',
    iso3: 'EGY',
    isArabianCountry: true,
    isKhalijiCountry: false,
    flag: '🇪🇬',
    order: 16,
  ),
  Countries(
    name: 'El Salvador',
    nameAr: 'السلفادور',
    dialCode: '+503',
    currency: 'USD',
    iso2: 'SV',
    iso3: 'SLV',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇸🇻',
    order: 0,
  ),
  Countries(
    name: 'Equatorial Guinea',
    nameAr: 'غينيا الاستوائية',
    dialCode: '+240',
    currency: 'XAF',
    iso2: 'GQ',
    iso3: 'GNQ',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇶',
    order: 0,
  ),
  Countries(
    name: 'Eritrea',
    nameAr: 'إريتريا',
    dialCode: '+291',
    currency: 'ERN',
    iso2: 'ER',
    iso3: 'ERI',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇪🇷',
    order: 0,
  ),
  Countries(
    name: 'Estonia',
    nameAr: 'إستونيا',
    dialCode: '+372',
    currency: 'EUR',
    iso2: 'EE',
    iso3: 'EST',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇪🇪',
    order: 0,
  ),
  Countries(
    name: 'Ethiopia',
    nameAr: 'إثيوبيا',
    dialCode: '+251',
    currency: 'ETB',
    iso2: 'ET',
    iso3: 'ETH',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇪🇹',
    order: 0,
  ),
  Countries(
    name: 'Faroe Islands',
    nameAr: 'جزر فايرو',
    dialCode: '+298',
    currency: 'DKK',
    iso2: 'FO',
    iso3: 'FRO',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇫🇴',
    order: 0,
  ),
  Countries(
    name: 'Falkland Islands',
    nameAr: 'جزر فوكلاند',
    dialCode: '+500',
    currency: 'FKP',
    iso2: 'FK',
    iso3: 'FLK',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇫🇰',
    order: 0,
  ),
  Countries(
    name: 'Fiji',
    nameAr: 'جزر فيجي',
    dialCode: '+679',
    currency: 'FJD',
    iso2: 'FJ',
    iso3: 'FJI',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇫🇯',
    order: 0,
  ),
  Countries(
    name: 'Finland',
    nameAr: 'فنلندا',
    dialCode: '+358',
    currency: 'EUR',
    iso2: 'FI',
    iso3: 'FIN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇫🇮',
    order: 0,
  ),
  Countries(
    name: 'France',
    nameAr: 'فرنسا',
    dialCode: '+33',
    currency: 'EUR',
    iso2: 'FR',
    iso3: 'FRA',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇫🇷',
    order: 0,
  ),
  Countries(
    name: 'French Polynesia',
    nameAr: 'بولينزيا الفرنسية',
    dialCode: '+689',
    currency: 'XPF',
    iso2: 'PF',
    iso3: 'PYF',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇵🇫',
    order: 0,
  ),
  Countries(
    name: 'Gabon',
    nameAr: 'الجابون',
    dialCode: '+241',
    currency: 'XAF',
    iso2: 'GA',
    iso3: 'GAB',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇦',
    order: 0,
  ),
  Countries(
    name: 'Gambia',
    nameAr: 'جامبيا',
    dialCode: '+220',
    currency: 'GMD',
    iso2: 'GM',
    iso3: 'GMB',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇲',
    order: 0,
  ),
  Countries(
    name: 'Georgia',
    nameAr: 'جورجيا',
    dialCode: '+995',
    currency: 'GEL',
    iso2: 'GE',
    iso3: 'GEO',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇪',
    order: 0,
  ),
  Countries(
    name: 'Gibraltar',
    nameAr: 'جبل طارق',
    dialCode: '+350',
    currency: 'GIP',
    iso2: 'GI',
    iso3: 'GIB',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇮',
    order: 0,
  ),
  Countries(
    name: 'Germany',
    nameAr: 'ألمانيا',
    dialCode: '+49',
    currency: 'EUR',
    iso2: 'DE',
    iso3: 'DEU',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇩🇪',
    order: 0,
  ),
  Countries(
    name: 'Ghana',
    nameAr: 'غانا',
    dialCode: '+233',
    currency: 'GHS',
    iso2: 'GH',
    iso3: 'GHA',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇭',
    order: 0,
  ),
  Countries(
    name: 'Greece',
    nameAr: 'اليونان',
    dialCode: '+30',
    currency: 'EUR',
    iso2: 'GR',
    iso3: 'GRC',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇷',
    order: 0,
  ),
  Countries(
    name: 'Greenland',
    nameAr: 'جرينلاند',
    dialCode: '+299',
    currency: 'DKK',
    iso2: 'GL',
    iso3: 'GRL',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇱',
    order: 0,
  ),
  Countries(
    name: 'Guadeloupe',
    nameAr: 'جواديلوب',
    dialCode: '+590',
    currency: 'EUR',
    iso2: 'GP',
    iso3: 'GLP',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇵',
    order: 0,
  ),
  Countries(
    name: 'Grenada',
    nameAr: 'غرينادا',
    dialCode: '+1473',
    currency: 'XCD',
    iso2: 'GD',
    iso3: 'GRD',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇩',
    order: 0,
  ),
  Countries(
    name: 'Guernsey',
    nameAr: 'جيرنزي',
    dialCode: '+44',
    currency: 'GBP',
    iso2: 'GG',
    iso3: 'GGY',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇬',
    order: 0,
  ),
  Countries(
    name: 'Guatemala',
    nameAr: 'جواتيمالا',
    dialCode: '+502',
    currency: 'GTQ',
    iso2: 'GT',
    iso3: 'GTM',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇹',
    order: 0,
  ),
  Countries(
    name: 'Guam',
    nameAr: 'جوام',
    dialCode: '+1671',
    currency: 'USD',
    iso2: 'GU',
    iso3: 'GUM',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇺',
    order: 0,
  ),
  Countries(
    name: 'Guinea',
    nameAr: 'غينيا',
    dialCode: '+224',
    currency: 'GNF',
    iso2: 'GN',
    iso3: 'GIN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇳',
    order: 0,
  ),
  Countries(
    name: 'Guinea-Bissau',
    nameAr: 'غينيا بيساو',
    dialCode: '+245',
    currency: 'XOF',
    iso2: 'GW',
    iso3: 'GNB',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇼',
    order: 0,
  ),
  Countries(
    name: 'Guyana',
    nameAr: 'جيانا',
    dialCode: '+592',
    currency: 'GYD',
    iso2: 'GY',
    iso3: 'GUY',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇬🇾',
    order: 0,
  ),
  Countries(
    name: 'Haiti',
    nameAr: 'هايتي',
    dialCode: '+509',
    currency: 'HTG',
    iso2: 'HT',
    iso3: 'HTI',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇭🇹',
    order: 0,
  ),
  Countries(
    name: 'Heard Island and McDonald Islands',
    nameAr: 'جزيرة هيرد وجزر ماكدونالد',
    dialCode: '+ ',
    currency: 'AUD',
    iso2: 'HM',
    iso3: 'HMD',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇭🇲',
    order: 0,
  ),
  Countries(
    name: 'Jordan',
    nameAr: 'الأردن',
    dialCode: '+962',
    currency: 'JOD',
    iso2: 'JO',
    iso3: 'JOR',
    isArabianCountry: true,
    isKhalijiCountry: false,
    flag: '🇯🇴',
    order: 4,
  ),
  Countries(
    name: 'Yemen',
    nameAr: 'اليمن',
    dialCode: '+967',
    currency: 'YER',
    iso2: 'YE',
    iso3: 'YEM',
    isArabianCountry: true,
    isKhalijiCountry: false,
    flag: '🇾🇪',
    order: 3,
  ),
  Countries(
    name: 'Honduras',
    nameAr: 'هندوراس',
    dialCode: '+504',
    currency: 'HNL',
    iso2: 'HN',
    iso3: 'HND',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇭🇳',
    order: 0,
  ),
  Countries(
    name: 'Hong Kong',
    nameAr: 'هونغ كونغ SAR',
    dialCode: '+852',
    currency: 'HKD',
    iso2: 'HK',
    iso3: 'HKG',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇭🇰',
    order: 0,
  ),
  Countries(
    name: 'Hungary',
    nameAr: 'المجر',
    dialCode: '+36',
    currency: 'HUF',
    iso2: 'HU',
    iso3: 'HUN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇭🇺',
    order: 0,
  ),
  Countries(
    name: 'Iceland',
    nameAr: 'أيسلندا',
    dialCode: '+354',
    currency: 'ISK',
    iso2: 'IS',
    iso3: 'ISL',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇮🇸',
    order: 0,
  ),
  Countries(
    name: 'India',
    nameAr: 'الهند',
    dialCode: '+91',
    currency: 'INR',
    iso2: 'IN',
    iso3: 'IND',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇮🇳',
    order: 0,
  ),
  Countries(
    name: 'Indonesia',
    nameAr: 'إندونيسيا',
    dialCode: '+62',
    currency: 'IDR',
    iso2: 'ID',
    iso3: 'IDN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇮🇩',
    order: 0,
  ),
  Countries(
    name: 'Iran',
    nameAr: 'إيران',
    dialCode: '+98',
    currency: 'IRR',
    iso2: 'IR',
    iso3: 'IRN',
    isArabianCountry: false,
    isKhalijiCountry: false,
    flag: '🇮🇷',
    order: 0,
  ),
  Countries(
    name: 'Iraq',
    nameAr: 'العراق',
    dialCode: '+964',
    currency: 'IQD',
    iso2: 'IQ',
    iso3: 'IRQ',
    isArabianCountry: true,
    isKhalijiCountry: false,
    flag: '🇮🇶',
    order: 6,
  ),
];
